// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBwQ_XQuW4j1Gg9L3tbLcyaOKBJ7qL2NU',
    appId: '1:369896627923:web:3108cae6fbfad2ef9dbe26',
    messagingSenderId: '369896627923',
    projectId: 'baedal-food-delivery',
    authDomain: 'baedal-food-delivery.firebaseapp.com',
    storageBucket: 'baedal-food-delivery.firebasestorage.app',
    measurementId: 'G-NSG1YHX0YF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgvlMn5x9qMnT_F2uICNoXU33-KshJmQs',
    appId: '1:369896627923:android:92e1485db6222b129dbe26',
    messagingSenderId: '369896627923',
    projectId: 'baedal-food-delivery',
    storageBucket: 'baedal-food-delivery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJhvY390us1R_a_HVKkP9N5wh9IXYR540',
    appId: '1:369896627923:ios:275fbc7a0eb3afbc9dbe26',
    messagingSenderId: '369896627923',
    projectId: 'baedal-food-delivery',
    storageBucket: 'baedal-food-delivery.firebasestorage.app',
    iosBundleId: 'com.baedal.app',
  );
}
